sudo: false

addons:
  apt:
    packages:
      - libgmp-dev

install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version

script:
  - stack setup --no-terminal
  - stack build --ghc-options=-Werror --no-terminal
  - stack test --ghc-options=-Werror --no-terminal

  # detecting dead code in this project
  - stack exec ghc-pkg expose ghc
  - "! (stack exec -- dead-code-detection --root Main -isrc -idriver -i .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/autogen/ | grep -v Paths_dead_code_detection)"
  - "! (stack exec -- dead-code-detection --root Main -isrc -itest -i .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/autogen/ | grep -v Paths_dead_code_detection)"

cache:
  directories:
    - $HOME/.stack
