version: "0.8.1"
synopsis: detect dead code in haskell projects
description: detect dead code in haskell projects
category: Development
maintainer: Sönke Hahn <soenkehahn@gmail.com>
license: BSD3

github: soenkehahn/dead-code-detection

extra-source-files:
  README.md

dependencies:
  - base == 4.*
  - silently
  - getopt-generics == 0.12.* || == 0.13.*
  - ghc
  - Glob
  - string-conversions
  - graph-wrapper
  - containers
  - uniplate
  - ghc-paths
  - gitrev
  - directory

executables:
  dead-code-detection:
    main: Main.hs
    ghc-options: >
      -Wall
      -fno-warn-name-shadowing
      -fwarn-incomplete-uni-patterns
      -fwarn-incomplete-record-updates
    source-dirs:
      - src
      - driver

tests:
  spec:
    main: Main.hs
    ghc-options: >
      -Wall
      -fno-warn-name-shadowing
      -fwarn-incomplete-record-updates
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - mockery
      - interpolate
      - filepath
